"""rebild db

Revision ID: 18418f250f4c
Revises: a0f20f38eba7
Create Date: 2026-03-02 20:03:37.618807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18418f250f4c'
down_revision: Union[str, Sequence[str], None] = 'a0f20f38eba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_statuses_id'), 'statuses', ['id'], unique=False)
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.add_column('applicants', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('middle_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'applicants', ['phone'])
    op.drop_column('applicants', 'address')
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'founded_year',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['name'])
    op.add_column('educations', sa.Column('applicant_id', sa.Integer(), nullable=False))
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('educations_resume_id_fkey'), 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'applicants', ['applicant_id'], ['id'])
    op.drop_column('educations', 'resume_id')
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'resumes', ['applicant_id'])
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('applicant_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['applicant_id'])
    op.create_unique_constraint(None, 'users', ['role_id'])
    op.create_unique_constraint(None, 'users', ['company_id'])
    op.create_foreign_key(None, 'users', 'applicants', ['applicant_id'], ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'password_hash')
    op.add_column('vacancies', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.add_column('vacancies', sa.Column('experience_id', sa.Integer(), nullable=False))
    op.add_column('vacancies', sa.Column('status_id', sa.Integer(), nullable=False))
    op.alter_column('vacancies', 'employment_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'work_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vacancies', 'salary_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'salary_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vacancies', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'vacancies', 'experiences', ['experience_id'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'currencies', ['currency_id'], ['id'])
    op.drop_column('vacancies', 'is_active')
    op.drop_column('vacancies', 'currency')
    op.drop_column('vacancies', 'experience_required')
    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('work_experiences', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('vacancies', sa.Column('experience_required', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vacancies', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vacancies', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.alter_column('vacancies', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vacancies', 'salary_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'salary_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vacancies', 'work_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'employment_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vacancies', 'status_id')
    op.drop_column('vacancies', 'experience_id')
    op.drop_column('vacancies', 'currency_id')
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'applicant_id')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'resumes', type_='unique')
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('educations', sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key(op.f('educations_resume_id_fkey'), 'educations', 'resumes', ['resume_id'], ['id'])
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('educations', 'applicant_id')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.alter_column('companies', 'founded_year',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('applicants', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applicants', type_='unique')
    op.drop_column('applicants', 'middle_name')
    op.drop_column('applicants', 'first_name')
    op.drop_column('applicants', 'last_name')
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('profiles_applicant_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('profiles_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey')),
    sa.UniqueConstraint('applicant_id', name=op.f('profiles_applicant_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('company_id', name=op.f('profiles_company_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_statuses_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
