"""initial clean schema

Revision ID: 2a33f7a4b7c5
Revises: 
Create Date: 2026-04-24 21:50:43.742290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a33f7a4b7c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
