"""upgrade company table

Revision ID: 45a113671e2f
Revises: 479b42134ab2
Create Date: 2026-04-08 22:08:52.478037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a113671e2f'
down_revision: Union[str, Sequence[str], None] = '479b42134ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
