"""upgrade company table

Revision ID: 479b42134ab2
Revises: 9ebdc8d12e25
Create Date: 2026-04-03 18:07:50.389667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479b42134ab2'
down_revision: Union[str, Sequence[str], None] = '9ebdc8d12e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_company_types_id'), 'company_types', ['id'], unique=False)
    op.add_column('companies', sa.Column('company_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_companies_company_type_id'), 'companies', ['company_type_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'company_types', ['company_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_company_type_id'), table_name='companies')
    op.drop_column('companies', 'company_type_id')
    op.drop_index(op.f('ix_company_types_id'), table_name='company_types')
    op.drop_table('company_types')
    # ### end Alembic commands ###
