"""initial clean schema

Revision ID: 4d5381ec22a1
Revises: 00278f77c402
Create Date: 2026-04-29 17:57:36.112354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d5381ec22a1'
down_revision: Union[str, Sequence[str], None] = '00278f77c402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_vacancy_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover_letter', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('applications_resume_id_fkey')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('applications_vacancy_id_fkey')),
    sa.PrimaryKeyConstraint('vacancy_id', 'resume_id', name=op.f('applications_pkey')),
    sa.UniqueConstraint('vacancy_id', 'resume_id', name=op.f('uq_applications_vacancy_resume'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_applications_vacancy_id'), 'applications', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###
