"""initial_schema

Revision ID: 8a62a740b821
Revises: 2ec60e20ecc1
Create Date: 2026-05-24 19:31:21.427540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a62a740b821'
down_revision: Union[str, Sequence[str], None] = '2ec60e20ecc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_messages_read_at'), 'messages', ['read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_read_at'), table_name='messages')
    op.drop_column('messages', 'read_at')
    # ### end Alembic commands ###
