"""create table change_resume and favoritevacancy

Revision ID: 9c83c8d8988f
Revises: 0da3d8117d5b
Create Date: 2026-05-12 13:09:38.805745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c83c8d8988f'
down_revision: Union[str, Sequence[str], None] = '0da3d8117d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', name='uq_favorite_vacancies_vacancy_id')
    )
    op.create_index(op.f('ix_favorite_vacancies_id'), 'favorite_vacancies', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_vacancies_vacancy_id'), 'favorite_vacancies', ['vacancy_id'], unique=False)
    op.create_table('resume_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_changes_id'), 'resume_changes', ['id'], unique=False)
    op.create_index(op.f('ix_resume_changes_resume_id'), 'resume_changes', ['resume_id'], unique=False)
    op.create_table('resume_favorite_vacancies',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('favorite_vacancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_vacancy_id'], ['favorite_vacancies.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('resume_id', 'favorite_vacancy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_favorite_vacancies')
    op.drop_index(op.f('ix_resume_changes_resume_id'), table_name='resume_changes')
    op.drop_index(op.f('ix_resume_changes_id'), table_name='resume_changes')
    op.drop_table('resume_changes')
    op.drop_index(op.f('ix_favorite_vacancies_vacancy_id'), table_name='favorite_vacancies')
    op.drop_index(op.f('ix_favorite_vacancies_id'), table_name='favorite_vacancies')
    op.drop_table('favorite_vacancies')
    # ### end Alembic commands ###
