"""update tables

Revision ID: a0f20f38eba7
Revises: 2c0cc6d8c636
Create Date: 2026-02-23 16:18:15.956825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f20f38eba7'
down_revision: Union[str, Sequence[str], None] = '2c0cc6d8c636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_status_key'), 'applications', type_='unique')
    op.add_column('vacancies', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'city_id')
    op.create_unique_constraint(op.f('applications_status_key'), 'applications', ['status'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
