"""rebild db

Revision ID: d51ee614121a
Revises: f012eacd7cbe
Create Date: 2026-03-02 21:35:39.230432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51ee614121a'
down_revision: Union[str, Sequence[str], None] = 'f012eacd7cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('applicant_id', sa.Integer(), nullable=False))
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('educations_resume_id_fkey'), 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'applicants', ['applicant_id'], ['id'])
    op.drop_column('educations', 'resume_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key(op.f('educations_resume_id_fkey'), 'educations', 'resumes', ['resume_id'], ['id'])
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('educations', 'applicant_id')
    # ### end Alembic commands ###
