"""rebild db

Revision ID: f012eacd7cbe
Revises: 18418f250f4c
Create Date: 2026-03-02 21:34:31.683786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f012eacd7cbe'
down_revision: Union[str, Sequence[str], None] = '18418f250f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('educations_applicant_id_fkey'), 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'resumes', ['resume_id'], ['id'])
    op.drop_column('educations', 'applicant_id')
    op.drop_constraint(op.f('resumes_applicant_id_key'), 'resumes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('resumes_applicant_id_key'), 'resumes', ['applicant_id'], postgresql_nulls_not_distinct=False)
    op.add_column('educations', sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key(op.f('educations_applicant_id_fkey'), 'educations', 'applicants', ['applicant_id'], ['id'])
    op.alter_column('educations', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('educations', 'resume_id')
    # ### end Alembic commands ###
